### ISSUE TITLE
What's the relationship between this and SNMP#NET?

### ISSUE THREAD

**Issue by lextm** [araditc/Arad.SnmpSharp#2]
The code in this repo has enough similarities with the [original SNMP#NET codebase](https://github.com/rqx110/SnmpSharpNet?tab=License-1-ov-file) (since 2008, released under LGPL).

You must disclose the relationship if your implementation is upon that, as the copyright laws require. And since you don't own the original copyrights, you cannot relicense the source files under GPL.

**Comment by ammarheidari** [comment]
This library based on SNMP#NET, that optimize and  updated for .NETCORE 8. You can get more information at about section.

**Comment by lextm** [comment]
An important part of the copyright law system is that it requires derived works to honor the rules (more than just the about section),

1. You should restore the original `AssemblyInfo.cs` and Milan's original copyright statement. Like I said, your work is a derivative and you don't own the original copyright. You can add similar statements for your modifications.
2. LGPL has other requirements you must meet.
3. You cannot mark the license as GPL 3. LGPL and GPL are different licenses.

Please consult your lawyer for more guidance.
